/**
 * Purchase Order models and types for Synkventory.
 */

// =============================================================================
// ENUMS
// =============================================================================

export enum PurchaseOrderStatus {
  DRAFT = 'draft',
  PENDING_APPROVAL = 'pending_approval',
  APPROVED = 'approved',
  ORDERED = 'ordered',
  PARTIALLY_RECEIVED = 'partially_received',
  RECEIVED = 'received',
  CANCELLED = 'cancelled',
}

export enum PurchaseOrderPriority {
  LOW = 'low',
  NORMAL = 'normal',
  HIGH = 'high',
  URGENT = 'urgent',
}

// =============================================================================
// LINE ITEM INTERFACES
// =============================================================================

export interface IPurchaseOrderLineItem {
  id: string;
  purchaseOrderId: string;
  itemId: string;
  quantityOrdered: number;
  quantityReceived: number;
  unitPrice: number;
  lineTotal: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  quantityRemaining: number;
}

export interface IPurchaseOrderLineItemWithItem extends IPurchaseOrderLineItem {
  itemName?: string;
  itemSku?: string;
  currentQuantity?: number;
  reorderPoint?: number;
}

export interface IPurchaseOrderLineItemCreate {
  itemId: string;
  quantityOrdered: number;
  unitPrice: number;
  notes?: string;
}

// =============================================================================
// PURCHASE ORDER INTERFACES
// =============================================================================

export interface IPurchaseOrderListItem {
  id: string;
  poNumber: string;
  supplierName?: string;
  status: string;
  priority: string;
  totalAmount: number;
  orderDate?: string;
  expectedDate?: string;
  receivedDate?: string;
  autoGenerated: boolean;
  createdAt: string;
  itemCount: number;
  itemsReceived: number;
  requestedByName?: string;
  isOverdue: boolean;
}

export interface IPurchaseOrder {
  id: string;
  tenantId: string;
  poNumber: string;
  supplierName?: string;
  supplierContact?: string;
  supplierEmail?: string;
  supplierPhone?: string;
  status: string;
  priority: string;
  orderDate?: string;
  expectedDate?: string;
  receivedDate?: string;
  receivingLocationId?: string;
  requestedById?: string;
  approvedById?: string;
  notes?: string;
  externalReference?: string;
  subtotal: number;
  taxAmount: number;
  shippingCost: number;
  totalAmount: number;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
  lineItems: IPurchaseOrderLineItemWithItem[];
  requestedByName?: string;
  approvedByName?: string;
  receivingLocationName?: string;
  isOverdue: boolean;
}

export interface IPurchaseOrderCreate {
  supplierName?: string;
  supplierContact?: string;
  supplierEmail?: string;
  supplierPhone?: string;
  priority?: string;
  expectedDate?: string;
  receivingLocationId?: string;
  notes?: string;
  externalReference?: string;
  lineItems?: IPurchaseOrderLineItemCreate[];
  requestedById?: string;
}

export interface IPurchaseOrderUpdate {
  supplierName?: string;
  supplierContact?: string;
  supplierEmail?: string;
  supplierPhone?: string;
  priority?: string;
  expectedDate?: string;
  receivingLocationId?: string;
  notes?: string;
  externalReference?: string;
  taxAmount?: number;
  shippingCost?: number;
}

// =============================================================================
// LOW STOCK INTERFACES
// =============================================================================

export interface ILowStockItem {
  id: string;
  name: string;
  sku: string;
  currentQuantity: number;
  reorderPoint: number;
  unitPrice: number;
  shortage: number;
  suggestedQuantity: number;
}

export interface ILowStockSuggestion {
  items: ILowStockItem[];
  totalItems: number;
  estimatedTotal: number;
}

// =============================================================================
// STATS INTERFACE
// =============================================================================

export interface IPurchaseOrderStats {
  total: number;
  draft: number;
  pendingApproval: number;
  approved: number;
  ordered: number;
  partiallyReceived: number;
  received: number;
  cancelled: number;
  overdue: number;
  totalValuePending: number;
}

// =============================================================================
// RECEIVE INTERFACES
// =============================================================================

export interface IReceivedLot {
  lotNumber: string;
  serialNumber?: string | null;
  quantity: number;
  expirationDate?: string | null;
  manufactureDate?: string | null;
}

export interface IReceiveLineItem {
  lineItemId: string;
  quantityReceived: number;
  notes?: string;
  lots?: IReceivedLot[];
}

export interface IReceiveItemsRequest {
  items: IReceiveLineItem[];
  notes?: string;
  receivedDate?: string;
}

// =============================================================================
// HELPER CLASS
// =============================================================================

export class PurchaseOrderHelpers {
  static getStatusLabel(status: string): string {
    const labels: Record<string, string> = {
      [PurchaseOrderStatus.DRAFT]: 'Draft',
      [PurchaseOrderStatus.PENDING_APPROVAL]: 'Pending Approval',
      [PurchaseOrderStatus.APPROVED]: 'Approved',
      [PurchaseOrderStatus.ORDERED]: 'Ordered',
      [PurchaseOrderStatus.PARTIALLY_RECEIVED]: 'Partially Received',
      [PurchaseOrderStatus.RECEIVED]: 'Received',
      [PurchaseOrderStatus.CANCELLED]: 'Cancelled',
    };
    return labels[status] || status;
  }

  static getStatusSeverity(status: string): 'success' | 'info' | 'warn' | 'danger' | 'secondary' | 'contrast' {
    const severities: Record<string, 'success' | 'info' | 'warn' | 'danger' | 'secondary' | 'contrast'> = {
      [PurchaseOrderStatus.DRAFT]: 'secondary',
      [PurchaseOrderStatus.PENDING_APPROVAL]: 'warn',
      [PurchaseOrderStatus.APPROVED]: 'info',
      [PurchaseOrderStatus.ORDERED]: 'info',
      [PurchaseOrderStatus.PARTIALLY_RECEIVED]: 'warn',
      [PurchaseOrderStatus.RECEIVED]: 'success',
      [PurchaseOrderStatus.CANCELLED]: 'danger',
    };
    return severities[status] || 'secondary';
  }

  static getPriorityLabel(priority: string): string {
    const labels: Record<string, string> = {
      [PurchaseOrderPriority.LOW]: 'Low',
      [PurchaseOrderPriority.NORMAL]: 'Normal',
      [PurchaseOrderPriority.HIGH]: 'High',
      [PurchaseOrderPriority.URGENT]: 'Urgent',
    };
    return labels[priority] || priority;
  }

  static getPrioritySeverity(priority: string): 'success' | 'info' | 'warn' | 'danger' | 'secondary' | 'contrast' {
    const severities: Record<string, 'success' | 'info' | 'warn' | 'danger' | 'secondary' | 'contrast'> = {
      [PurchaseOrderPriority.LOW]: 'secondary',
      [PurchaseOrderPriority.NORMAL]: 'info',
      [PurchaseOrderPriority.HIGH]: 'warn',
      [PurchaseOrderPriority.URGENT]: 'danger',
    };
    return severities[priority] || 'secondary';
  }

  static canEdit(status: string): boolean {
    return status === PurchaseOrderStatus.DRAFT || status === PurchaseOrderStatus.PENDING_APPROVAL;
  }

  static canApprove(status: string): boolean {
    return status === PurchaseOrderStatus.PENDING_APPROVAL;
  }

  static canOrder(status: string): boolean {
    return status === PurchaseOrderStatus.APPROVED;
  }

  static canReceive(status: string): boolean {
    return status === PurchaseOrderStatus.ORDERED || status === PurchaseOrderStatus.PARTIALLY_RECEIVED;
  }

  static canCancel(status: string): boolean {
    return ![PurchaseOrderStatus.RECEIVED, PurchaseOrderStatus.CANCELLED].includes(status as PurchaseOrderStatus);
  }

  static canDelete(status: string): boolean {
    return status === PurchaseOrderStatus.DRAFT;
  }

  static getNextStatuses(status: string): PurchaseOrderStatus[] {
    const transitions: Record<string, PurchaseOrderStatus[]> = {
      [PurchaseOrderStatus.DRAFT]: [PurchaseOrderStatus.PENDING_APPROVAL, PurchaseOrderStatus.APPROVED],
      [PurchaseOrderStatus.PENDING_APPROVAL]: [PurchaseOrderStatus.APPROVED, PurchaseOrderStatus.DRAFT],
      [PurchaseOrderStatus.APPROVED]: [PurchaseOrderStatus.ORDERED],
      [PurchaseOrderStatus.ORDERED]: [PurchaseOrderStatus.PARTIALLY_RECEIVED, PurchaseOrderStatus.RECEIVED],
      [PurchaseOrderStatus.PARTIALLY_RECEIVED]: [PurchaseOrderStatus.RECEIVED],
      [PurchaseOrderStatus.RECEIVED]: [],
      [PurchaseOrderStatus.CANCELLED]: [],
    };
    return transitions[status] || [];
  }
}
